LabWebApp/urls.py
from django import urls
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from LabWebApp import views
from LabWebProject import settings
from django.conf.urls import url


app_name = 'LabWebApp'
urlpatterns = [
    path('search', views.search, name='search'),
    path('user', views.userSelf, name='userSelf'),
    path('sign-in', views.signIn, name='signIn'),
    path('', views.main, name='main'),
    path('news-category/<str:news_category>/<str:page_number>', views.newsCategory, name='newsCategory'),
    path('news/<str:news_url>', views.newsDetail, name='newsDetail'),
    path('research/research-field', views.researchField, name='researchField'),
    path('research/thesis', views.researchThesis, name='researchThesis'),
    path('research/work', views.researchWork, name='researchWork'),
    path('research/platform', views.researchPlatform, name='researchPlatform'),
    path('member/teacher/detail', views.memberTeacherDetail, name='memberTeacherDetail'),
    path('member/student', views.memberStudent, name='memberStudent'),
    path('member/student/<str:student_url>', views.memberStudentDetail, name='memberStudentDetail'),
    path('about', views.about, name='about'),
    path('graduate/student', views.graduateStudent, name='graduateStudent'),
    path('graduate/message', views.graduateMessage, name='graduateMessage'),
    path('test', views.test, name='test'),
    path('admin', views.admin, name='admin'),
    path('admin/news', views.adminNews, name='adminNews'),
    path('admin/news/<str:news_url>', views.adminNewsDetail, name='adminNewsDetail'),
    path('admin/slider', views.adminSlider, name='adminSlider'),
    path('admin/statistic', views.adminStatistic, name='adminStatistic'),
    path('admin/user', views.adminUser, name='adminUser'),
    path('admin/user/<str:user_url>', views.adminUserDetail, name='adminUserDetail'),
    path('admin/research-field', views.adminResearchField, name='adminResearchField'),
    path('admin/research-thesis', views.adminResearchThesis, name='adminResearchThesis'),
    path('admin/research-work', views.adminResearchWork, name='adminResearchWork'),
    path('admin/research-work/<str:work_url>', views.adminResearchWorkDetail, name='adminResearchWorkDetail'),
    path('admin/message', views.adminMessage, name='adminMessage'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = views.pageNotFound

LabWebProject/urls.py
from django.urls import include, path


urlpatterns = [
    path('', include('LabWebApp.urls', namespace='LabWebApp')),
]

templates/404Standard.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script type="text/javascript" src="{% static 'js/tool/jquery-3-7-1.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/self/404.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/self/404.css' %}">
    </head>
    <body>
        <div class="container">
            <div class="svg">
                <img class="svg_rose" src="{% static 'svg/rose.svg' %}">
                <img class="svg_404" src="{% static 'svg/404.svg' %}">
            </div>
            <div class="info">
                <label class="info_404"><span class="mark mark_left">“</span>{{ error_info }}<span class="mark mark_right">”</span></label>
            </div>
        </div>
        <label class="contact">联系开发者：<a href="mailto:2562521178@qq.com?subject=问题反馈">2562521178@qq.com</a>　联系管理员：<a href="mailto:lzx2562521178@outlook.com?subject=问题反馈">lzx2562521178@outlook.com</a></label>
        <div class="split_link"></div>
        <div class="link">
            <a href="{% url 'LabWebApp:main' %}">首页 |</a>
            <a href="{% url 'LabWebApp:newsCategory' news_category='all' page_number='1' %}">新闻公告 |</a>
            <a href="{% url 'LabWebApp:researchField' %}">学术研究 |</a>
            <a href="{% url 'LabWebApp:memberTeacherDetail' %}">实验室成员 |</a>
            <a href="{% url 'LabWebApp:about' %}">关于我们 |</a>
            <a href="{% url 'LabWebApp:main' %}">毕业寄语</a>
        </div>
    </body>
</html>

templates/adminBase.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script type="text/javascript" src="{% static 'js/tool/jquery-3-7-1.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/self/adminNavigation.css' %}">
        {% block head %}
        {% endblock %}
    </head>
    <body>
        <div class="navigation_top">
            <a class="to_main" href="{% url 'LabWebApp:main' %}">DASI 实验室</a>
            <a class="to_admin" href="{% url 'LabWebApp:admin' %}">控制台</a>
            <a class="user" href="{% url 'LabWebApp:userSelf' %}">
                <div class="user_img"></div>
                <script type="text/javascript">
                    let photoPath = '/media/{{ user.photo }}';
                    $('.user_img').css('background-image', "url('" + photoPath + "')");
                </script>
                <label class="user_name">{{ user.username }}</label>
            </a>
        </div>
        <div class="navigation_left">
            <img class="svg_control" src="{% static 'svg/control.svg' %}">
            <div class="navigation_left_inner">
                <a class="to_admin_change to_admin_news" href="{% url 'LabWebApp:adminNews' %}">新闻公告</a>
                <a class="to_admin_change to_admin_slider" href="{% url 'LabWebApp:adminSlider' %}">轮播图</a>
                <a class="to_admin_change to_admin_statistic" href="{% url 'LabWebApp:adminStatistic' %}">统计数据</a>
                <a class="to_admin_change to_admin_user" href="{% url 'LabWebApp:adminUser' %}">实验室成员</a>
                <a class="to_admin_change to_admin_research_field" href="{% url 'LabWebApp:adminResearchField' %}">研究方向</a>
                <a class="to_admin_change to_admin_thesis" href="{% url 'LabWebApp:adminResearchThesis' %}">论文专利</a>
                <a class="to_admin_change to_admin_work" href="{% url 'LabWebApp:adminResearchWork' %}">学术著作</a>
                <a class="to_admin_change to_admin_message" href="{% url 'LabWebApp:adminMessage' %}">毕业寄语</a>
                <a class="to_admin_change jto_admin_tips" href="{% url 'LabWebApp:main' %}">其他</a>
            </div>
        </div>
        {% block body %}
        {% endblock %}
    </body>
</html>

templates/adminResearchWork.html
{% extends 'adminBase.html' %}
{% load static %}
{% block head %}
    <title>学术著作</title>
    <script type="text/javascript" src="{% static 'js/tool/sweetalert2.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/self/adminResearchWork.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/self/adminResearchWork.css' %}">
{% endblock head %}
{% block body %}
    {% csrf_token %}
    <div class="operate_panel_container">
        <label class="operate_panel_title">学术著作控制台</label>
        <button type="button" class="btn_add" onclick="window.location.href = 'research-work/add'">新增著作</button>
        <div class="split_work"></div>
        <div class="operate_panel">
            {% for item in data %}
                <div class="operate_panel_item">
                    <label class="item_number">{{ item.work_num }}</label>
                    <a class="to_work" href="{{ item.work_link }}">{{ item.work_title }}</a>
                    <label class="item_time">出版时间：{{ item.work_date }}</label>
                    <a class="to_detail" href="{% url 'LabWebApp:adminResearchWorkDetail' work_url=item.work_id %}">编辑</a>
                    <button type="button" class="btn_delete" id="{{ item.work_id }}" onclick="deleteWork(this)">删除</button>
                    <div class="split_item"></div>
                </div>
            {% endfor %}
        </div>
        <div class="correct_alert">
            <img class="correct_alert_img" src="{% static 'svg/correct.svg' %}">
            <label class="correct_alert_text">已删除</label>
        </div>
    </div>
{% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script type="text/javascript" src="{% static 'js/tool/jquery-3-7-1.js' %}"></script>
        <script defer type="text/javascript" src="{% static 'js/self/navigation.js' %}"></script>
        <script defer type="text/javascript" src="{% static 'js/self/footer.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/self/navigation.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/self/footer.css' %}">
        {% block head %}
        {% endblock head %}
    </head>
    <body>
        {% csrf_token %}
        <div class="navigation">
            <a class="logo" href="{% url 'LabWebApp:main' %}">
                <img class="svg_whu" src="{% static 'svg/whu.svg' %}">
                <img class="svg_dasi" src="{% static 'svg/dasi.svg' %}">
            </a>
            <div class="nav">
                <a class="el el_1" href="{% url 'LabWebApp:newsCategory' news_category='all' page_number='1' %}">新闻公告</a>
                <a class="el el_2" href="{% url 'LabWebApp:researchField' %}">学术研究</a>
                <a class="el el_3" href="{% url 'LabWebApp:memberTeacherDetail' %}">实验室成员</a>
                <a class="el el_4" href="{% url 'LabWebApp:about' %}">关于我们</a>
                <a class="el el_5" href="{% url 'LabWebApp:graduateMessage' %}">毕业印象</a>
                <div class="split_el"></div>
                <div class="nav_out nav_out_1">
                    <div class="nav_in">
                        <a class="el_in" href="{% url 'LabWebApp:newsCategory' news_category='research' page_number='1' %}">学术科研</a>
                        <a class="el_in" href="{% url 'LabWebApp:newsCategory' news_category='achievement' page_number='1' %}">团队喜讯</a>
                        <a class="el_in" href="{% url 'LabWebApp:newsCategory' news_category='lecture' page_number='1' %}">讲座论坛</a>
                        <a class="el_in" href="{% url 'LabWebApp:newsCategory' news_category='culture' page_number='1' %}">生活文化</a>
                    </div>
                    <img class="svg_building" src="{% static 'svg/building.svg' %}">
                </div>
                <div class="nav_out nav_out_2">
                    <div class="nav_in">
                        <a class="el_in" href="{% url 'LabWebApp:researchField' %}">研究方向</a>
                        <a class="el_in" href="{% url 'LabWebApp:researchThesis' %}">论文专利</a>
                        <a class="el_in" href="{% url 'LabWebApp:researchWork' %}">学术著作</a>
                        <a class="el_in" href="{% url 'LabWebApp:researchPlatform' %}">研究平台</a>
                    </div>
                    <img class="svg_building" src="{% static 'svg/building.svg' %}">
                </div>
                <div class="nav_out nav_out_3">
                    <div class="nav_in">
                        <a class="el_in" href="{% url 'LabWebApp:memberTeacherDetail' %}">教　　师</a>
                        <a class="el_in" href="{% url 'LabWebApp:memberStudent' %}">学生团队</a>
                    </div>
                    <img class="svg_building" src="{% static 'svg/building.svg' %}">
                </div>
                <div class="nav_out nav_out_5">
                    <div class="nav_in">
                        <a class="el_in" href="{% url 'LabWebApp:graduateMessage' %}">毕业寄语</a>
                        <a class="el_in" href="{% url 'LabWebApp:graduateStudent' %}">毕业生</a>
                    </div>
                    <img class="svg_building" src="{% static 'svg/building.svg' %}">
                </div>
            </div>
            <img class="svg_navigation" src="{% static 'svg/navigation.svg' %}">
            <div class="svg_navigation_cover"></div>
            <div class="nav_hide">
                <img class="svg_close" src="{% static 'svg/close.svg' %}">
                <img class="svg_building_hide" src="{% static 'svg/building.svg' %}">
                <div class="nav_hide_block_1">
                    <a class="hide_block_el_1" href="{% url 'LabWebApp:newsCategory' news_category='all' page_number='1' %}">新闻公告</a>
                    <div class="nav_hide_block_2">
                        <a class="hide_block_el_2" href="{% url 'LabWebApp:newsCategory' news_category='research' page_number='1' %}">学术科研</a>
                        <a class="hide_block_el_2" href="{% url 'LabWebApp:newsCategory' news_category='achievement' page_number='1' %}">团队喜讯</a>
                        <a class="hide_block_el_2" href="{% url 'LabWebApp:newsCategory' news_category='lecture' page_number='1' %}">讲座论坛</a>
                        <a class="hide_block_el_2" href="{% url 'LabWebApp:newsCategory' news_category='culture' page_number='1' %}">生活文化</a>
                    </div>
                </div>
                <div class="nav_hide_block_1">
                    <a class="hide_block_el_1" href="{% url 'LabWebApp:researchField' %}">学术研究</a>
                    <div class="nav_hide_block_2">
                        <a class="hide_block_el_2" href="{% url 'LabWebApp:researchField' %}">研究方向</a>
                        <a class="hide_block_el_2" href="{% url 'LabWebApp:researchThesis' %}">论文专利</a>
                        <a class="hide_block_el_2" href="{% url 'LabWebApp:researchWork' %}">学术著作</a>
                        <a class="hide_block_el_2" href="{% url 'LabWebApp:researchPlatform' %}">研究平台</a>
                    </div>
                </div>
                <div class="nav_hide_block_1">
                    <a class="hide_block_el_1" href="{% url 'LabWebApp:memberTeacherDetail' %}">实验室成员</a>
                    <div class="nav_hide_block_2">
                        <a class="hide_block_el_2" href="{% url 'LabWebApp:memberTeacherDetail' %}">教师</a>
                        <a class="hide_block_el_2" href="{% url 'LabWebApp:memberStudent' %}">学生团队</a>
                    </div>
                </div>
                <div class="nav_hide_block_1">
                    <a class="hide_block_el_1" href="{% url 'LabWebApp:about' %}">关于我们</a>
                </div>
                <div class="nav_hide_block_1">
                    <a class="hide_block_el_1" href="{% url 'LabWebApp:graduateMessage' %}">毕业印象</a>
                    <div class="nav_hide_block_2">
                        <a class="hide_block_el_2" href="{% url 'LabWebApp:graduateMessage' %}">毕业寄语</a>
                        <a class="hide_block_el_2" href="{% url 'LabWebApp:graduateStudent' %}">毕业生</a>
                    </div>
                </div>
            </div>
            <div class="form_search">
                <div class="init_show">
                    <input type="text" class="input_search" id="input_search" onkeypress="searchEnter(this, event)">
                    <div class="occupy" onclick="search(this)"></div>
                    <img class="svg_search" src="{% static 'svg/search.svg' %}">
                </div>
                <div class="search_active">
                    <img class="svg_search_active" src="{% static 'svg/search_active.svg' %}">
                </div>
            </div>
            <a class="user" href="{% url 'LabWebApp:userSelf' %}">
                <div class="user_img" style="background-image: url('/media/{{ user.photo }}');"></div>
                <label class="user_name">{{ user.username }}</label>
            </a>
            <div class="side_label">
                <div class="side_input">
                    <input type="text" class="input_search_side" id="input_search_side" onkeypress="searchEnter(this, event)">
                    <div class="occupy_side" onclick="search(this)"></div>
                    <img class="svg_search_side" src="{% static 'svg/search.svg' %}">
                </div>
                <a class="user_img_side" href="{% url 'LabWebApp:userSelf' %}" style="background-image: url('/media/{{ user.photo }}');"></a>
            </div>
        </div>
        {% block body %}
        {% endblock body %}
        <div class="footer">
            <div class="footer_navigation">
                <div class="nav_block_1">
                    <a class="block_el_1" href="{% url 'LabWebApp:newsCategory' news_category='all' page_number='1' %}">新闻公告</a>
                    <div class="nav_block_2">
                        <a class="block_el_2" href="{% url 'LabWebApp:newsCategory' news_category='research' page_number='1' %}">学术科研</a>
                        <a class="block_el_2" href="{% url 'LabWebApp:newsCategory' news_category='achievement' page_number='1' %}">团队喜讯</a>
                        <a class="block_el_2" href="{% url 'LabWebApp:newsCategory' news_category='lecture' page_number='1' %}">讲座论坛</a>
                        <a class="block_el_2" href="{% url 'LabWebApp:newsCategory' news_category='culture' page_number='1' %}">生活文化</a>
                    </div>
                </div>
                <div class="nav_block_1">
                    <a class="block_el_1" href="{% url 'LabWebApp:researchField' %}">学术研究</a>
                    <div class="nav_block_2">
                        <a class="block_el_2" href="{% url 'LabWebApp:researchField' %}">研究方向</a>
                        <a class="block_el_2" href="{% url 'LabWebApp:researchThesis' %}">论文专利</a>
                        <a class="block_el_2" href="{% url 'LabWebApp:researchWork' %}">学术著作</a>
                        <a class="block_el_2" href="{% url 'LabWebApp:researchPlatform' %}">研究平台</a>
                    </div>
                </div>
                <div class="nav_block_1">
                    <a class="block_el_1" href="{% url 'LabWebApp:memberTeacherDetail' %}">实验室成员</a>
                    <div class="nav_block_2">
                        <a class="block_el_2" href="{% url 'LabWebApp:memberTeacherDetail' %}">教师</a>
                        <a class="block_el_2" href="{% url 'LabWebApp:memberStudent' %}">学生团队</a>
                    </div>
                </div>
                <div class="nav_block_1">
                    <a class="block_el_1" href="{% url 'LabWebApp:about' %}">关于我们</a>
                </div>
                <div class="nav_block_1">
                    <a class="block_el_1" href="{% url 'LabWebApp:graduateMessage' %}">毕业印象</a>
                    <div class="nav_block_2">
                        <a class="block_el_2" href="{% url 'LabWebApp:graduateMessage' %}">毕业寄语</a>
                        <a class="block_el_2" href="{% url 'LabWebApp:graduateStudent' %}">毕业生</a>
                    </div>
                </div>
            </div>
            <div class="footer_info">
                <div class="split_footer"></div>
                <div class="link">
                    <a href="http://www.moe.gov.cn/">中华人民共和国教育部 |</a>
                    <a href="https://www.whu.edu.cn/">武汉大学 |</a>
                    <a href="https://www.lib.whu.edu.cn/">武汉大学图书馆 |</a>
                    <a href="https://ehall.whu.edu.cn/">武汉大学信息门户 |</a>
                    <a href="https://bdi.whu.edu.cn/">武汉大学大数据研究院</a>
                </div>
                <div class="info_content">地址：湖北省武汉市武昌区八一路299号大数据研究院 | 邮箱：hong@whu.edu.cn | 公众号：珞珈大数据</div>
                <div class="info_content">版权所有：武汉大学数据科学与智能应用实验室 | Copyright © 2023 All Rights Reserved</div>
            </div>
        </div>
    </body>
</html>

templates/graduateMessage.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title>毕业寄语</title>
    <script type="text/javascript" src="{% static 'js/tool/masonry.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/self/footer.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/self/graduateMessage.js' %}" defer></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/self/graduateMessage.css' %}">
{% endblock head %}
{% block body %}
    {% csrf_token %}
    <div class="head_photo_cover">
        <img class="head_photo" src="{% static 'img/top.png' %}">
    </div>
    <div class="content">
        <div class="breadcrumb_navigation">
            <img class="svg_location" src="{% static 'svg/location.svg' %}"></img>
            <label class="current">当前位置：</label>
            <a class="breadcrumb_item" href="{% url 'LabWebApp:main' %}">首页</a>
            <label class="next">&nbsp;&gt;&nbsp;</label>
            <a class="breadcrumb_item" href="">毕业印象</a>
            <label class="next">&nbsp;&gt;&nbsp;</label>
            <a class="breadcrumb_item" href="">毕业寄语</a>
        </div>
        <div class="split_top"></div>
        <div class="message_title">毕业寄语</div>
        <div class="content_inner">
            <div class="content_grid"></div>
        </div>
        <button type="button" class="tip" onclick="continueLoad()">点击加载更多</button>
    </div>
{% endblock body %}

templates/newsDetail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    {% csrf_token %}
    <title>{{ data.news_title }}</title>
    <script type="text/javascript" src="{% static 'js/self/footer.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/self/newsDetail.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/self/newsDetail.css' %}">
{% endblock head %}
{% block body %}
    <div class="head_photo_cover">
        <img class="head_photo" src="{% static 'img/top.png' %}">
    </div>
    <div class="content">
        <div class="breadcrumb_navigation">
            <img class="svg_location" src="{% static 'svg/location.svg' %}"></img>
            <label class="current">当前位置：</label>
            <a class="breadcrumb_item" href="{% url 'LabWebApp:main' %}">首页</a>
            <label class="next">&nbsp;&gt;&nbsp;</label>
            <a class="breadcrumb_item" href="{% url 'LabWebApp:newsCategory' news_category='all' page_number='1' %}">新闻公告</a>
            <label class="next">&nbsp;&gt;&nbsp;</label>
            <a class="breadcrumb_item" href="{% url 'LabWebApp:newsCategory' news_category=data.news_category_url page_number='1' %}">{{ data.news_category }}</a>
            <label class="next">&nbsp;&gt;&nbsp;</label>
            <a class="breadcrumb_item" href="">正文</a>
        </div>
        <div class="news_content">
            <div class="news_title">{{ data.news_title }}</div>
            <div class="block_info">
                <div class="info_news news_author">撰稿人：{{ data.news_author }}　摄影：{{ data.news_photographer }}</div>
                <div class="info_news news_post_datetime">发布时间：{{ data.news_post_datetime }}</div>
                <div class="split_main"></div>
            </div>
        </div>
    </div>
{% endblock body %}

templates/researchField.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    {% csrf_token %}
    <title>研究方向</title>
    <script type="text/javascript" src="{% static 'js/self/footer.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/self/researchField.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/self/researchField.css' %}">
{% endblock head %}
{% block body %}
    <div class="head_photo_cover">
        <img class="head_photo" src="{% static 'img/top.png' %}">
    </div>
    <div class="content">
        <div class="breadcrumb_navigation">
            <img class="svg_location" src="{% static 'svg/location.svg' %}"></img>
            <label class="current">当前位置：</label>
            <a class="breadcrumb_item" href="{% url 'LabWebApp:main' %}">首页</a>
            <label class="next">&nbsp;&gt;&nbsp;</label>
            <a class="breadcrumb_item" href="{% url 'LabWebApp:researchField' %}">学术研究</a>
            <label class="next">&nbsp;&gt;&nbsp;</label>
            <a class="breadcrumb_item" href="">研究方向</a>
        </div>
        <div class="content_inner">
            <div class="content_title">研究方向</div>
            <div class="content_subtitle">Research Field</div>
            <div class="split_content"></div>
        </div>
    </div>
{% endblock body %}

templates/researchThesis.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title>论文专利</title>
    <script type="text/javascript" src="{% static 'js/self/footer.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/self/researchThesis.css' %}">
{% endblock head %}
{% block body %}
    <div class="head_photo_cover">
        <img class="head_photo" src="{% static 'img/top.png' %}">
    </div>
    <div class="content">
        <div class="breadcrumb_navigation">
            <img class="svg_location" src="{% static 'svg/location.svg' %}"></img>
            <label class="current">当前位置：</label>
            <a class="breadcrumb_item" href="{% url 'LabWebApp:main' %}">首页</a>
            <label class="next">&nbsp;&gt;&nbsp;</label>
            <a class="breadcrumb_item" href="{% url 'LabWebApp:researchField' %}">学术研究</a>
            <label class="next">&nbsp;&gt;&nbsp;</label>
            <a class="breadcrumb_item" href="">论文专利</a>
        </div>
        <div class="content_inner">
            <div class="content_title">论文专利</div>
            <div class="content_subtitle">Thesis & Patent</div>
            <div class="split_content"></div>
            <div class="content_abstract">实验室师生在xxxx，xxxx等领域的xxxx、xxxx、xxxx、xxxx、xxxx等刊物发表有多篇论文，并申有多个专利</div>
        </div>
        <div class="thesis_list">
            {% for item in data %}
            <div class="thesis_item">
                <div class="thesis_item_content thesis_item_number">{{ item.thesis_number }}</div>
                <a class="thesis_item_content thesis_item_title" href="{{ item.thesis_link }}">{{ item.thesis_author }}，{{ item.thesis_title }}</a>
                <div class="thesis_item_content thesis_item_date">{{ item.thesis_date }}</div>
                <div class="split_thesis"></div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock body %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    {% csrf_token %}
    <title>综合搜索</title>
    <script type="text/javascript" src="{% static 'js/self/footer.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/self/search.css' %}">
{% endblock head %}
{% block body %}
    <div class="head_photo_cover">
        <img class="head_photo" src="{% static 'img/top.png' %}">
    </div>
    <div class="content">
        <div class="breadcrumb_navigation">
            <img class="svg_location" src="{% static 'svg/location.svg' %}"></img>
            <label class="current">当前位置：</label>
            <a class="breadcrumb_item" href="{% url 'LabWebApp:main' %}">首页</a>
            <label class="next">&nbsp;&gt;&nbsp;</label>
            <a class="breadcrumb_item" href="">综合搜索：{{ data.search_keyword }}</a>
        </div>
        <div class="split_content"></div>
        <div class="content_inner">
            <div class="no_result">{{ data.no_result }}</div>
            <div class="result_student">
                {% for student in data.result_student %}
                    <div class="result_student_item" onclick="window.location.href = './student/{{ student.student_id }}'">
                        <div class="student_photo" style="background-image: url('/media/{{ student.student_photo }}')">
                            <div class="student_grade">{{ student.student_grade }}</div>
                        </div>
                        <div class="student_name">{{ student.student_name }}</div>
                    </div>
                {% endfor %}
            </div>
            <div class="result_news">
                {% for news in data.result_news %}
                    <a class="result_news_item">
                        <a class="news_category_and_title" href="{% url 'LabWebApp:newsDetail' news_url=news.news_id %}">[{{ news.news_category }}] {{ news.news_title }}</a>
                        <div class="news_post_date">{{ news.news_post_date }}</div>
                        <div class="split_news"></div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock body %}